# Generated by Django 3.2.7 on 2021-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211021_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
