# Generated by Django 3.2.7 on 2021-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211026_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='content_one',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_three',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_two',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
