# Generated by Django 3.2.7 on 2021-10-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211030_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_three',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_two',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
