# Generated by Django 3.2.7 on 2021-11-07 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211030_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=254, null=True, validators=[django.core.validators.RegexValidator('^[^\\s].+[^\\s]$', 'Please ensure the text does not                             begin or end with whitespace')]),
        ),
    ]
