# Generated by Django 3.2.7 on 2021-11-03 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211030_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=254, null=True, validators=[django.core.validators.RegexValidator('/^[a-z][a-z\\s]*$/', 'Please enter a valid title                                  including only letters')]),
        ),
    ]
