# Generated by Django 3.2.7 on 2021-11-06 09:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=254, null=True, validators=[blog.models.validate_text]),
        ),
    ]
