# Generated by Django 3.2.7 on 2021-11-09 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211108_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_one',
            field=models.TextField(help_text='Minimum of 50 characters required', max_length=2000, null=True, validators=[django.core.validators.RegexValidator(message='Please only use text and numbers                         and common punctuation characters and @, or #', regex='^[a-zA-Z0-9,!?\\.\\(\\)@"\\\'#€¥£¢$ -]+$')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_three',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator(message='Please only use text and numbers                             and common punctuation characters and @, or #', regex='^[a-zA-Z0-9,!?\\.\\(\\)@"\\\'#€¥£¢$ -]+$')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_two',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator(message='Please only use text and numbers                         and common punctuation characters and @, or #', regex='^[a-zA-Z0-9,!?\\.\\(\\)@"\\\'#€¥£¢$ -]+$')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(help_text='Minimum of 10 characters required', max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Please only use text and numbers                     and common punctuation characters and @, or #', regex='^[a-zA-Z0-9,!?\\.\\(\\)@"\\\'#€¥£¢$ -]+$')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Minimum of 5 characters required', max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Please only use text and numbers                         and common punctuation characters and @, or #', regex='^[a-zA-Z0-9,!?\\.\\(\\)@"\\\'#€¥£¢$ -]+$')]),
        ),
    ]
