# Generated by Django 3.2.7 on 2021-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
