# Generated by Django 3.2.7 on 2021-10-13 07:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211005_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UK 4', 'UK 4'), ('UK 4.5', 'UK 4.5'), ('UK 5', 'UK 5'), ('UK 5.5', 'UK 5.5'), ('UK 6', 'UK 6'), ('UK 6.5', 'UK 6.5'), ('UK 7', 'UK 7'), ('UK 7.5', 'UK 7.5'), ('UK 8', 'UK 8'), ('UK 8.5', 'UK 8.5'), ('UK 9', 'UK 9'), ('UK 9.5', 'UK 9.5'), ('UK 10', 'UK 10'), ('UK 10.5', 'UK 10.5'), ('UK 11', 'UK 11'), ('UK 11.5', 'UK 11.5'), ('UK 12', 'UK 12'), ('UK 12.5', 'UK 12.5'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=129, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
