# Generated by Django 3.2.7 on 2021-10-30 00:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_parentcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Run', 'Run'), ('Cycle', 'Cycle'), ('Swim', 'Swim'), ('Nutrition', 'Nutrition')], max_length=24, null=True),
        ),
    ]
